// Code generated by goyacc -o expr.go -p expr expr.y. DO NOT EDIT.

//line expr.y:13

package main

import __yyfmt__ "fmt"

//line expr.y:14

import (
	"fmt"

	"math/big"
)

//line expr.y:28
type exprSymType struct {
	yys int
	num *big.Rat
}

const NUM = 57346

var exprToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'('",
	"')'",
	"NUM",
}
var exprStatenames = [...]string{}

const exprEofCode = 1
const exprErrCode = 2
const exprInitialStackSize = 16

//line expr.y:76
